# frozen_string_literal: true

source 'https://rubygems.org'

ruby '~> 2.4.0'

gem 'httparty'
gem 'oauth2'
gem 'sinatra', '>= 1.3.1', require: 'sinatra/base'

group :test do
  gem 'rack-test'
  gem 'rspec'
  gem 'webmock'
end
